\
from __future__ import annotations
import logging
from typing import Mapping, Any

from boto3 import Session

from resolvers.base_resolver import BaseResolver
from resolvers.registry import register_resolver
from utils.arn import ARN, extract_dependencies
from graph.resource_node import ResourceNode, NodeClassification

log = logging.getLogger(__name__)

# Optional: enable service-specific mypy-boto3 stubs.
# Uncomment if you have the correct stub package:
# from mypy_boto3_iam import IamClient as Boto3Client  # type: ignore[import]
# Otherwise fallback:
# from botocore.client import BaseClient as Boto3Client


@register_resolver("iam:policy")
class IamPolicyResolver(BaseResolver):
    """
    Auto-generated resolver for iam:Policy.
    Generated by tools/service_introspector.py.
    Safe to customize if the heuristic does not perfectly apply.
    """

    service = "iam"
    resource_type = "policy"
    resource_name = "Policy"
    cfn_type = 'AWS::IAM::Policy'
    deployment_mode = "l2"

    # Introspection metadata
    list_operation = 'list_policies'
    describe_operation = 'get_policy'
    id_fields = ['PolicyArn']
    summary_list_path = 'Policies'
    summary_arn_field = 'Arn'

    # ------------------------------------------------------------------
    # fetch_resource
    # ------------------------------------------------------------------
    def fetch_resource(self, arn: ARN) -> Mapping[str, Any]:
        """
        Call Describe*/Get* using IDs resolved from the ARN.

        ID Resolution Rules:
          1) id_fields ending in "Id"     → hierarchy match (e.g. InstanceId)
          2) id_fields ending in "Arn"    → full ARN
          3) id_fields ending in "Name"   → ARN.resource_id
          4) fallback: map last N ARN parts → id_fields

        For synthetic resources that don't have a native ARN, the ARN passed
        in is typically an "anchor" (e.g., the parent instance ARN).
        """
        if not self.describe_operation:
            raise RuntimeError(f"No describe_operation for {self.resource_name}")

        parts = arn.resource_parts
        values: dict[str, str] = {}
        hierarchy = dict(arn.resource_hierarchy())

        for key in self.id_fields:
            kl = key.lower()

            # InstanceId → instance
            if kl.endswith("id"):
                base = kl[:-2]
                if base in hierarchy:
                    values[key] = hierarchy[base]
                    continue

            # ResourceArn → full ARN
            if kl.endswith("arn"):
                values[key] = arn.raw
                continue

            # FunctionName / TableName → resource_id
            if kl.endswith("name") and arn.resource_id:
                values[key] = arn.resource_id
                continue

        # Fallback: map last N ARN parts to remaining id_fields
        if self.id_fields and len(values) < len(self.id_fields):
            needed = len(self.id_fields) - len(values)
            if len(parts) >= needed:
                for key, val in zip(
                    [k for k in self.id_fields if k not in values],
                    parts[-needed:]
                ):
                    values.setdefault(key, val)

        log.debug(
            "Calling %s.%s for %s with params %s",
            self.service,
            self.describe_operation,
            arn,
            values,
        )

        client = self.client_for(arn)
        fn = getattr(client, self.describe_operation)
        return fn(**values)

    # ------------------------------------------------------------------
    # to_node
    # ------------------------------------------------------------------
    def to_node(self, arn: ARN, raw: Mapping[str, Any]) -> ResourceNode:
        """
        Convert the raw Describe*/Get* output into a ResourceNode.
        This is uniform across all generated resolvers.
        """

        # unwrap: {"ResourceName": {...}} → {...}
        inner = raw.get(self.resource_name) if isinstance(raw, Mapping) else None
        props = inner if isinstance(inner, Mapping) else raw

        rid = arn.resource_id or "Root"
        logical_id = f"{self.resource_name}_{rid}"
        referenced = extract_dependencies(props)

        return ResourceNode(
            logical_id=logical_id,
            service=self.service,
            cfn_type=self.cfn_type,
            properties=dict(props),
            referenced_arns=referenced,
            classification=NodeClassification.RESOURCE,
            arns={"Primary": arn},  # backward compatible
        )
