// Import all syncers to trigger registerSyncer() side-effects
import './syncers/lambda'
import './syncers/iam'
import './syncers/connect'
import './syncers/connect-user'
import './syncers/connect-instance'
import './syncers/dynamodb'
import './syncers/s3'
import './syncers/sqs'
import './syncers/sns'
import './syncers/secrets-manager'
import './syncers/ssm'
import './syncers/eventbridge'
import './syncers/stepfunctions'
import './syncers/kms'
import './syncers/kinesis'
import './syncers/qconnect'
import './syncers/apigateway'
import './syncers/cloudfront'
import './syncers/cloudformation-stack'

export { getSyncer } from './registry'
export type { ResourceSyncer, SyncPushResult } from './syncer'
