from __future__ import annotations

from resolvers.base_resolver import BaseResolver
from resolvers.registry import register_resolver

# Optional: enable service-specific mypy-boto3 stubs.
# Uncomment if you have the correct stub package:
# from mypy_boto3_cloudwatch import CloudwatchClient as Boto3Client  # type: ignore[import]
# Otherwise fallback:
# from botocore.client import BaseClient as Boto3Client

@register_resolver("cloudwatch:dashboard")
class CloudwatchDashboardResolver(BaseResolver):
    """
    Auto-generated resolver for cloudwatch:Dashboard.
    Generated by tools/service_introspector.py.
    """

    service = "cloudwatch"
    resource_type = "dashboard"
    resource_name = "Dashboard"
    cfn_type = "AWS::CloudWatch::Dashboard"
    deployment_mode = "cfn"

    # Introspection metadata
    list_operation = 'list_dashboards'
    describe_operation = 'get_dashboard'
    id_fields = ['DashboardName']
    summary_list_path = 'DashboardEntries'
    summary_arn_field = 'DashboardArn'



@register_resolver("cloudwatch:metric-stream")
class CloudwatchMetricStreamResolver(BaseResolver):
    """
    Auto-generated resolver for cloudwatch:MetricStream.
    Generated by tools/service_introspector.py.
    """

    service = "cloudwatch"
    resource_type = "metric-stream"
    resource_name = "MetricStream"
    cfn_type = "AWS::CloudWatch::MetricStream"
    deployment_mode = "cfn"

    # Introspection metadata
    list_operation = 'list_metric_streams'
    describe_operation = 'get_metric_stream'
    id_fields = ['Name']
    summary_list_path = 'Entries'
    summary_arn_field = 'Arn'

