from __future__ import annotations

from resolvers.base_resolver import BaseResolver
from resolvers.registry import register_resolver

# Optional: enable service-specific mypy-boto3 stubs.
# Uncomment if you have the correct stub package:
# from mypy_boto3_dynamodb import DynamodbClient as Boto3Client  # type: ignore[import]
# Otherwise fallback:
# from botocore.client import BaseClient as Boto3Client

@register_resolver("dynamodb:export")
class DynamodbExportResolver(BaseResolver):
    """
    Auto-generated resolver for dynamodb:Export.
    Generated by tools/service_introspector.py.
    """

    service = "dynamodb"
    resource_type = "export"
    resource_name = "Export"
    cfn_type = None
    deployment_mode = "boto3"

    # Introspection metadata
    list_operation = 'list_exports'
    describe_operation = 'describe_export'
    id_fields = ['ExportArn']
    summary_list_path = 'ExportSummaries'
    summary_arn_field = 'ExportArn'



@register_resolver("dynamodb:import")
class DynamodbImportResolver(BaseResolver):
    """
    Auto-generated resolver for dynamodb:Import.
    Generated by tools/service_introspector.py.
    """

    service = "dynamodb"
    resource_type = "import"
    resource_name = "Import"
    cfn_type = None
    deployment_mode = "boto3"

    # Introspection metadata
    list_operation = 'list_imports'
    describe_operation = 'describe_import'
    id_fields = ['ImportArn']
    summary_list_path = 'ImportSummaryList'
    summary_arn_field = 'ImportArn'



@register_resolver("dynamodb:table")
class DynamodbTableResolver(BaseResolver):
    """
    Auto-generated resolver for dynamodb:Table.
    Generated by tools/service_introspector.py.
    """

    service = "dynamodb"
    resource_type = "table"
    resource_name = "Table"
    cfn_type = "AWS::DynamoDB::Table"
    deployment_mode = "cfn"

    # Introspection metadata
    list_operation = None
    describe_operation = 'describe_table'
    id_fields = ['TableName']
    summary_list_path = None
    summary_arn_field = 'TableArn'

