from __future__ import annotations

from resolvers.base_resolver import BaseResolver
from resolvers.registry import register_resolver

# Optional: enable service-specific mypy-boto3 stubs.
# Uncomment if you have the correct stub package:
# from mypy_boto3_iam import IamClient as Boto3Client  # type: ignore[import]
# Otherwise fallback:
# from botocore.client import BaseClient as Boto3Client

@register_resolver("iam:account-authorization-detail")
class IamAccountAuthorizationDetailResolver(BaseResolver):
    """
    Auto-generated resolver for iam:AccountAuthorizationDetail.
    Generated by tools/service_introspector.py.
    """

    service = "iam"
    resource_type = "account-authorization-detail"
    resource_name = "AccountAuthorizationDetail"
    cfn_type = None
    deployment_mode = "boto3"

    # Introspection metadata
    list_operation = 'get_account_authorization_details'
    describe_operation = 'get_account_authorization_details'
    id_fields = []
    summary_list_path = 'UserDetailList'
    summary_arn_field = 'Arn'



@register_resolver("iam:group")
class IamGroupResolver(BaseResolver):
    """
    Auto-generated resolver for iam:Group.
    Generated by tools/service_introspector.py.
    """

    service = "iam"
    resource_type = "group"
    resource_name = "Group"
    cfn_type = "AWS::IAM::Group"
    deployment_mode = "cfn"

    # Introspection metadata
    list_operation = 'get_group'
    describe_operation = 'get_group'
    id_fields = ['GroupName']
    summary_list_path = 'Users'
    summary_arn_field = 'Arn'



@register_resolver("iam:instance-profile")
class IamInstanceProfileResolver(BaseResolver):
    """
    Auto-generated resolver for iam:InstanceProfile.
    Generated by tools/service_introspector.py.
    """

    service = "iam"
    resource_type = "instance-profile"
    resource_name = "InstanceProfile"
    cfn_type = "AWS::IAM::InstanceProfile"
    deployment_mode = "cfn"

    # Introspection metadata
    list_operation = 'list_instance_profiles'
    describe_operation = 'get_instance_profile'
    id_fields = ['InstanceProfileName']
    summary_list_path = 'InstanceProfiles'
    summary_arn_field = 'Arn'



@register_resolver("iam:open-id-connect-provider")
class IamOpenIDConnectProviderResolver(BaseResolver):
    """
    Auto-generated resolver for iam:OpenIDConnectProvider.
    Generated by tools/service_introspector.py.
    """

    service = "iam"
    resource_type = "open-id-connect-provider"
    resource_name = "OpenIDConnectProvider"
    cfn_type = "AWS::IAM::OIDCProvider"
    deployment_mode = "cfn"

    # Introspection metadata
    list_operation = 'list_open_id_connect_providers'
    describe_operation = 'get_open_id_connect_provider'
    id_fields = ['OpenIDConnectProviderArn']
    summary_list_path = 'OpenIDConnectProviderList'
    summary_arn_field = 'Arn'



@register_resolver("iam:policy")
class IamPolicyResolver(BaseResolver):
    """
    Auto-generated resolver for iam:Policy.
    Generated by tools/service_introspector.py.
    """

    service = "iam"
    resource_type = "policy"
    resource_name = "Policy"
    cfn_type = "AWS::IAM::ManagedPolicy"
    deployment_mode = "cfn"

    # Introspection metadata
    list_operation = 'list_policies'
    describe_operation = 'get_policy'
    id_fields = ['PolicyArn']
    summary_list_path = 'Policies'
    summary_arn_field = 'Arn'



@register_resolver("iam:role")
class IamRoleResolver(BaseResolver):
    """
    Auto-generated resolver for iam:Role.
    Generated by tools/service_introspector.py.
    """

    service = "iam"
    resource_type = "role"
    resource_name = "Role"
    cfn_type = "AWS::IAM::Role"
    deployment_mode = "cfn"

    # Introspection metadata
    list_operation = 'list_roles'
    describe_operation = 'get_role'
    id_fields = ['RoleName']
    summary_list_path = 'Roles'
    summary_arn_field = 'Arn'



@register_resolver("iam:saml-provider")
class IamSAMLProviderResolver(BaseResolver):
    """
    Auto-generated resolver for iam:SAMLProvider.
    Generated by tools/service_introspector.py.
    """

    service = "iam"
    resource_type = "saml-provider"
    resource_name = "SAMLProvider"
    cfn_type = "AWS::IAM::SAMLProvider"
    deployment_mode = "cfn"

    # Introspection metadata
    list_operation = 'list_saml_providers'
    describe_operation = 'get_saml_provider'
    id_fields = ['SAMLProviderArn']
    summary_list_path = 'SAMLProviderList'
    summary_arn_field = 'Arn'



@register_resolver("iam:server-certificate")
class IamServerCertificateResolver(BaseResolver):
    """
    Auto-generated resolver for iam:ServerCertificate.
    Generated by tools/service_introspector.py.
    """

    service = "iam"
    resource_type = "server-certificate"
    resource_name = "ServerCertificate"
    cfn_type = "AWS::IAM::ServerCertificate"
    deployment_mode = "cfn"

    # Introspection metadata
    list_operation = 'list_server_certificates'
    describe_operation = 'get_server_certificate'
    id_fields = ['ServerCertificateName']
    summary_list_path = 'ServerCertificateMetadataList'
    summary_arn_field = 'Arn'



@register_resolver("iam:user")
class IamUserResolver(BaseResolver):
    """
    Auto-generated resolver for iam:User.
    Generated by tools/service_introspector.py.
    """

    service = "iam"
    resource_type = "user"
    resource_name = "User"
    cfn_type = "AWS::IAM::User"
    deployment_mode = "cfn"

    # Introspection metadata
    list_operation = 'list_users'
    describe_operation = 'get_user'
    id_fields = ['UserName']
    summary_list_path = 'Users'
    summary_arn_field = 'Arn'

