from __future__ import annotations

from resolvers.base_resolver import BaseResolver
from resolvers.registry import register_resolver

# Optional: enable service-specific mypy-boto3 stubs.
# Uncomment if you have the correct stub package:
# from mypy_boto3_logs import LogsClient as Boto3Client  # type: ignore[import]
# Otherwise fallback:
# from botocore.client import BaseClient as Boto3Client

@register_resolver("logs:log-anomaly-detector")
class LogsLogAnomalyDetectorResolver(BaseResolver):
    """
    Auto-generated resolver for logs:LogAnomalyDetector.
    Generated by tools/service_introspector.py.
    """

    service = "logs"
    resource_type = "log-anomaly-detector"
    resource_name = "LogAnomalyDetector"
    cfn_type = None
    deployment_mode = "boto3"

    # Introspection metadata
    list_operation = 'list_log_anomaly_detectors'
    describe_operation = 'get_log_anomaly_detector'
    id_fields = ['anomalyDetectorArn']
    summary_list_path = 'anomalyDetectors'
    summary_arn_field = 'anomalyDetectorArn'



@register_resolver("logs:log-group")
class LogsLogGroupResolver(BaseResolver):
    """
    Auto-generated resolver for logs:LogGroup.
    Generated by tools/service_introspector.py.
    """

    service = "logs"
    resource_type = "log-group"
    resource_name = "LogGroup"
    cfn_type = "AWS::Logs::LogGroup"
    deployment_mode = "cfn"

    # Introspection metadata
    list_operation = 'list_log_groups'
    describe_operation = 'describe_log_groups'
    id_fields = []
    summary_list_path = 'logGroups'
    summary_arn_field = 'logGroupArn'



@register_resolver("logs:scheduled-query")
class LogsScheduledQueryResolver(BaseResolver):
    """
    Auto-generated resolver for logs:ScheduledQuery.
    Generated by tools/service_introspector.py.
    """

    service = "logs"
    resource_type = "scheduled-query"
    resource_name = "ScheduledQuery"
    cfn_type = None
    deployment_mode = "boto3"

    # Introspection metadata
    list_operation = 'list_scheduled_queries'
    describe_operation = 'get_scheduled_query'
    id_fields = ['identifier']
    summary_list_path = 'scheduledQueries'
    summary_arn_field = 'scheduledQueryArn'

