from __future__ import annotations

from resolvers.base_resolver import BaseResolver
from resolvers.registry import register_resolver

# Optional: enable service-specific mypy-boto3 stubs.
# Uncomment if you have the correct stub package:
# from mypy_boto3_scheduler import SchedulerClient as Boto3Client  # type: ignore[import]
# Otherwise fallback:
# from botocore.client import BaseClient as Boto3Client

@register_resolver("scheduler:schedule")
class SchedulerScheduleResolver(BaseResolver):
    """
    Auto-generated resolver for scheduler:Schedule.
    Generated by tools/service_introspector.py.
    """

    service = "scheduler"
    resource_type = "schedule"
    resource_name = "Schedule"
    cfn_type = "AWS::Scheduler::Schedule"
    deployment_mode = "cfn"

    # Introspection metadata
    list_operation = 'list_schedules'
    describe_operation = 'get_schedule'
    id_fields = ['Name', 'GroupName']
    summary_list_path = 'Schedules'
    summary_arn_field = 'Arn'



@register_resolver("scheduler:schedule-group")
class SchedulerScheduleGroupResolver(BaseResolver):
    """
    Auto-generated resolver for scheduler:ScheduleGroup.
    Generated by tools/service_introspector.py.
    """

    service = "scheduler"
    resource_type = "schedule-group"
    resource_name = "ScheduleGroup"
    cfn_type = "AWS::Scheduler::ScheduleGroup"
    deployment_mode = "cfn"

    # Introspection metadata
    list_operation = 'list_schedule_groups'
    describe_operation = 'get_schedule_group'
    id_fields = ['Name']
    summary_list_path = 'ScheduleGroups'
    summary_arn_field = 'Arn'

