from __future__ import annotations

from resolvers.base_resolver import BaseResolver
from resolvers.registry import register_resolver

# Optional: enable service-specific mypy-boto3 stubs.
# Uncomment if you have the correct stub package:
# from mypy_boto3_secretsmanager import SecretsmanagerClient as Boto3Client  # type: ignore[import]
# Otherwise fallback:
# from botocore.client import BaseClient as Boto3Client

@register_resolver("secretsmanager:secret")
class SecretsmanagerSecretResolver(BaseResolver):
    """
    Auto-generated resolver for secretsmanager:Secret.
    Generated by tools/service_introspector.py.
    """

    service = "secretsmanager"
    resource_type = "secret"
    resource_name = "Secret"
    cfn_type = "AWS::SecretsManager::Secret"
    deployment_mode = "cfn"

    # Introspection metadata
    list_operation = 'list_secrets'
    describe_operation = 'describe_secret'
    id_fields = ['SecretId']
    summary_list_path = 'SecretList'
    summary_arn_field = 'ARN'

