from __future__ import annotations

from resolvers.base_resolver import BaseResolver
from resolvers.registry import register_resolver

# Optional: enable service-specific mypy-boto3 stubs.
# Uncomment if you have the correct stub package:
# from mypy_boto3_sns import SnsClient as Boto3Client  # type: ignore[import]
# Otherwise fallback:
# from botocore.client import BaseClient as Boto3Client

@register_resolver("sns:platform-application")
class SnsPlatformApplicationResolver(BaseResolver):
    """
    Auto-generated resolver for sns:PlatformApplication.
    Generated by tools/service_introspector.py.
    """

    service = "sns"
    resource_type = "platform-application"
    resource_name = "PlatformApplication"
    cfn_type = "AWS::SNS::PlatformApplication"
    deployment_mode = "cfn"

    # Introspection metadata
    list_operation = 'list_platform_applications'
    describe_operation = 'get_platform_application_attributes'
    id_fields = ['PlatformApplicationArn']
    summary_list_path = 'PlatformApplications'
    summary_arn_field = 'PlatformApplicationArn'



@register_resolver("sns:subscription")
class SnsSubscriptionResolver(BaseResolver):
    """
    Auto-generated resolver for sns:Subscription.
    Generated by tools/service_introspector.py.
    """

    service = "sns"
    resource_type = "subscription"
    resource_name = "Subscription"
    cfn_type = "AWS::SNS::Subscription"
    deployment_mode = "cfn"

    # Introspection metadata
    list_operation = 'list_subscriptions'
    describe_operation = 'get_subscription_attributes'
    id_fields = ['SubscriptionArn']
    summary_list_path = 'Subscriptions'
    summary_arn_field = 'SubscriptionArn'



@register_resolver("sns:topic")
class SnsTopicResolver(BaseResolver):
    """
    Auto-generated resolver for sns:Topic.
    Generated by tools/service_introspector.py.
    """

    service = "sns"
    resource_type = "topic"
    resource_name = "Topic"
    cfn_type = "AWS::SNS::Topic"
    deployment_mode = "cfn"

    # Introspection metadata
    list_operation = 'list_topics'
    describe_operation = 'get_topic_attributes'
    id_fields = ['TopicArn']
    summary_list_path = 'Topics'
    summary_arn_field = 'TopicArn'

