from __future__ import annotations

from resolvers.base_resolver import BaseResolver
from resolvers.registry import register_resolver

# Optional: enable service-specific mypy-boto3 stubs.
# Uncomment if you have the correct stub package:
# from mypy_boto3_ssm import SsmClient as Boto3Client  # type: ignore[import]
# Otherwise fallback:
# from botocore.client import BaseClient as Boto3Client

@register_resolver("ssm:ops-metadata")
class SsmOpsMetadataResolver(BaseResolver):
    """
    Auto-generated resolver for ssm:OpsMetadata.
    Generated by tools/service_introspector.py.
    """

    service = "ssm"
    resource_type = "ops-metadata"
    resource_name = "OpsMetadata"
    cfn_type = "AWS::SSM::OpsMetadata"
    deployment_mode = "cfn"

    # Introspection metadata
    list_operation = 'list_ops_metadata'
    describe_operation = 'get_ops_metadata'
    id_fields = ['OpsMetadataArn']
    summary_list_path = 'OpsMetadataList'
    summary_arn_field = 'OpsMetadataArn'



@register_resolver("ssm:parameter")
class SsmParameterResolver(BaseResolver):
    """
    Auto-generated resolver for ssm:Parameter.
    Generated by tools/service_introspector.py.
    """

    service = "ssm"
    resource_type = "parameter"
    resource_name = "Parameter"
    cfn_type = "AWS::SSM::Parameter"
    deployment_mode = "cfn"

    # Introspection metadata
    list_operation = 'get_parameters'
    describe_operation = 'get_parameter'
    id_fields = ['Name']
    summary_list_path = 'Parameters'
    summary_arn_field = 'ARN'



@register_resolver("ssm:parameters-by-path")
class SsmParametersByPathResolver(BaseResolver):
    """
    Auto-generated resolver for ssm:ParametersByPath.
    Generated by tools/service_introspector.py.
    """

    service = "ssm"
    resource_type = "parameters-by-path"
    resource_name = "ParametersByPath"
    cfn_type = None
    deployment_mode = "boto3"

    # Introspection metadata
    list_operation = 'get_parameters_by_path'
    describe_operation = 'get_parameters_by_path'
    id_fields = []
    summary_list_path = 'Parameters'
    summary_arn_field = 'ARN'

