\
from __future__ import annotations
import logging
from typing import Mapping, Any, Dict, List

from boto3 import Session
from botocore.exceptions import ClientError

from resolvers.base_resolver import BaseResolver
from resolvers.registry import register_resolver
from utils.arn import ARN, extract_dependencies
from graph.resource_node import ResourceNode, NodeClassification

log = logging.getLogger(__name__)

# Optional: enable service-specific mypy-boto3 stubs.
# Uncomment if you have the correct stub package:
# from mypy_boto3_connect import ConnectClient as Boto3Client  # type: ignore[import]
# Otherwise fallback:
# from botocore.client import BaseClient as Boto3Client


@register_resolver("connect:instance")
class ConnectInstanceResolver(BaseResolver):
    """
    Auto-generated resolver for connect:Instance.
    Generated by tools/service_introspector.py.
    Safe to customize if the heuristic does not perfectly apply.
    """

    service = "connect"
    resource_type = "instance"
    resource_name = "Instance"
    cfn_type = 'AWS::Connect::Instance'
    deployment_mode = "cfn"

    # Introspection metadata
    list_operation = 'list_instances'
    describe_operation = 'describe_instance'
    id_fields = ['InstanceId']
    summary_list_path = 'InstanceSummaryList'
    summary_arn_field = 'Arn'
    storage_resource_types = [
        "CALL_RECORDINGS",
        "CHAT_TRANSCRIPTS",
        "SCHEDULED_REPORTS",
        "MEDIA_STREAMS",
        "CONTACT_TRACE_RECORDS",
    ]

    # ------------------------------------------------------------------
    # fetch_resource
    # ------------------------------------------------------------------
    def fetch_resource(self, arn: ARN) -> Mapping[str, Any]:
        """
        Call Describe*/Get* using IDs resolved from the ARN.

        ID Resolution Rules:
          1) id_fields ending in "Id"     → hierarchy match (e.g. InstanceId)
          2) id_fields ending in "Arn"    → full ARN
          3) id_fields ending in "Name"   → ARN.resource_id
          4) fallback: map last N ARN parts → id_fields

        For synthetic resources that don't have a native ARN, the ARN passed
        in is typically an "anchor" (e.g., the parent instance ARN).
        """
        if not self.describe_operation:
            raise RuntimeError(f"No describe_operation for {self.resource_name}")

        parts = arn.resource_parts
        values: dict[str, str] = {}
        hierarchy = dict(arn.resource_hierarchy())

        for key in self.id_fields:
            kl = key.lower()

            # InstanceId → instance
            if kl.endswith("id"):
                base = kl[:-2]
                if base in hierarchy:
                    values[key] = hierarchy[base]
                    continue

            # ResourceArn → full ARN
            if kl.endswith("arn"):
                values[key] = arn.raw
                continue

            # FunctionName / TableName → resource_id
            if kl.endswith("name") and arn.resource_id:
                values[key] = arn.resource_id
                continue

        # Fallback: map last N ARN parts to remaining id_fields
        if self.id_fields and len(values) < len(self.id_fields):
            needed = len(self.id_fields) - len(values)
            if len(parts) >= needed:
                for key, val in zip(
                    [k for k in self.id_fields if k not in values],
                    parts[-needed:]
                ):
                    values.setdefault(key, val)

        log.debug(
            "Calling %s.%s for %s with params %s",
            self.service,
            self.describe_operation,
            arn,
            values,
        )

        client = self.client_for(arn)
        fn = getattr(client, self.describe_operation)
        raw = fn(**values)

        # enrich with instance attributes + storage configs
        instance_id = values.get("InstanceId") or arn.resource_id
        props = raw.get(self.resource_name, {}) if isinstance(raw, Mapping) else {}
        props = dict(props) if isinstance(props, Mapping) else {}

        attributes = self._fetch_instance_attributes(client, instance_id)
        if attributes:
            props["Attributes"] = attributes

        storage_configs = self._fetch_storage_configs(client, instance_id)
        if storage_configs:
            props["StorageConfigs"] = storage_configs

        # Write back into raw payload so to_node still unwraps correctly
        if isinstance(raw, Mapping):
            raw = dict(raw)
            raw[self.resource_name] = props
        else:
            raw = {self.resource_name: props}

        return raw

    # ------------------------------------------------------------------
    # to_node
    # ------------------------------------------------------------------
    def to_node(self, arn: ARN, raw: Mapping[str, Any]) -> ResourceNode:
        """
        Convert the raw Describe*/Get* output into a ResourceNode.
        This is uniform across all generated resolvers.
        """

        # unwrap: {"ResourceName": {...}} → {...}
        inner = raw.get(self.resource_name) if isinstance(raw, Mapping) else None
        props = inner if isinstance(inner, Mapping) else raw

        rid = arn.resource_id or "Root"
        logical_id = f"{self.resource_name}_{rid}"
        referenced = extract_dependencies(props)

        return ResourceNode(
            logical_id=logical_id,
            service=self.service,
            cfn_type=self.cfn_type,
            properties=dict(props),
            referenced_arns=referenced,
            classification=NodeClassification.RESOURCE,
            arns={"Primary": arn},  # backward compatible
        )

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------
    def _fetch_instance_attributes(self, client, instance_id: str) -> List[Dict[str, Any]]:
        try:
            resp = client.list_instance_attributes(InstanceId=instance_id)
        except ClientError as e:
            log.debug("list_instance_attributes failed for %s: %s", instance_id, e)
            return []
        return resp.get("Attributes") or []

    def _fetch_storage_configs(self, client, instance_id: str) -> Dict[str, List[Dict[str, Any]]]:
        results: Dict[str, List[Dict[str, Any]]] = {}
        for resource_type in self.storage_resource_types:
            try:
                paginator = client.get_paginator("list_instance_storage_configs")
                pages = paginator.paginate(InstanceId=instance_id, ResourceType=resource_type)
                configs: List[Dict[str, Any]] = []
                for page in pages:
                    configs.extend(page.get("StorageConfigs") or [])
                if configs:
                    results[resource_type] = configs
            except ClientError as e:
                log.debug(
                    "list_instance_storage_configs failed for %s (%s): %s",
                    instance_id,
                    resource_type,
                    e,
                )
            except Exception as e:
                log.debug(
                    "Unexpected error listing storage configs for %s (%s): %s",
                    instance_id,
                    resource_type,
                    e,
                )
        return results
