/**
 * Per-account Lambda environment variable overrides.
 * Values here override the base env vars at deploy time.
 * Generated by aws-sync-tool — 2026-05-28
 */
export const ENV_OVERRIDES: Record<string, Record<string, Record<string, string>>> = {
  "797776209609": {

  }
};
