from __future__ import annotations

import json
import logging
from typing import Any, Dict, Optional

from utils.arn import ARN
from graph.dependency_graph import DependencyGraph, ResourceNode
from utils.json_encoder import AWSJSONEncoder
from utils.mapping_store import MappingStore

logger = logging.getLogger(__name__)

REF_RULES = {
    "s3": "Ref",
    "connect": "Ref",
    "lambda": "Arn",
    "dynamodb": "Arn",
    "iam": "Arn",
    "sns": "Arn",
    "sqs": "Arn",
}


class CloudFormationTemplateBuilder:
    """Serialize a dependency graph into a CloudFormation template."""

    def __init__(
        self,
        graph: DependencyGraph,
        *,
        mapping_store: Optional[MappingStore] = None,
        description: str = "Generated by aws-sync-tool",
    ) -> None:
        self.graph = graph
        self.mapping_store = mapping_store
        self.description = description

    # ------------------------------------------------------------------
    # Main build
    # ------------------------------------------------------------------
    def build_template(self) -> dict:
        resources: Dict[str, dict] = {}
        parameters: Dict[str, dict] = {}

        for lid in self.graph.topological_sort():
            node = self.graph.get_node(lid)

            # Skip reference-only nodes
            if not self._is_managed_by_cfn(node):
                parameters[f"{lid}Arn"] = {
                    "Type": "String",
                    "Description": f"External ARN for {lid}",
                }
                continue

            props = self._walk_and_replace_arns(node.properties)
            resources[lid] = {
                "Type": node.cfn_type,
                "Properties": props,
            }

        # Add any pending parameters collected by the link resolver
        pending = self.graph.metadata.get("PendingParams", {})
        for key, val in pending.items():
            parameters[key] = {
                "Type": "String",
                "Default": val,
                "Description": f"Auto-detected parameter for environment variable or link",
            }

        return {
            "AWSTemplateFormatVersion": "2010-09-09",
            "Description": self.description,
            "Parameters": parameters,
            "Resources": resources,
        }

    # ------------------------------------------------------------------
    # ARN substitution
    # ------------------------------------------------------------------
    def _walk_and_replace_arns(self, data: Any) -> Any:
        """Replace any ARNs in a nested structure with CFN references."""
        if isinstance(data, str) and data.startswith("arn:"):
            return self._arn_to_cfn(data) or data
        elif isinstance(data, dict):
            return {k: self._walk_and_replace_arns(v) for k, v in data.items()}
        elif isinstance(data, list):
            return [self._walk_and_replace_arns(v) for v in data]
        return data

    def _arn_to_cfn(self, arn_str: str) -> Optional[dict]:
        arn = ARN.try_parse(arn_str)
        if not arn:
            return None

        node = self.graph.get_node_by_arn(arn)
        if not node:
            return None

        rule = REF_RULES.get(node.service, "Arn")
        if rule == "Ref":
            return {"Ref": node.logical_id}
        else:
            return {"Fn::GetAtt": [node.logical_id, "Arn"]}

    # ------------------------------------------------------------------
    # Helper
    # ------------------------------------------------------------------
    def _is_managed_by_cfn(self, node: ResourceNode) -> bool:
        if not self.mapping_store:
            return not node.reference_only
        for rec in self.mapping_store.iter_all():
            if rec.logical_id == node.logical_id:
                return rec.management_mode in ("cfn", "cdk") and rec.managed_by_tool
        return not node.reference_only
