from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any, Dict
from string import Template


# =====================================================================
# Resolver class template
# =====================================================================
TEMPLATE = Template(r'''\
from __future__ import annotations
import logging
from typing import Mapping, Any

from boto3 import Session

from resolvers.base_resolver import BaseResolver
from resolvers.registry import register_resolver
from utils.arn import ARN, extract_dependencies
from graph.resource_node import ResourceNode, NodeClassification

log = logging.getLogger(__name__)

# Optional: enable service-specific mypy-boto3 stubs.
# Uncomment if you have the correct stub package:
# from mypy_boto3_${service} import ${stub_client} as Boto3Client  # type: ignore[import]
# Otherwise fallback:
# from botocore.client import BaseClient as Boto3Client


@register_resolver("${service}:${resource_key}")
class ${class_name}(BaseResolver):
    """
    Auto-generated resolver for ${service}:${resource_name}.
    Generated by tools/service_introspector.py.
    Safe to customize if the heuristic does not perfectly apply.
    """

    service = "${service}"
    resource_type = "${resource_key}"
    resource_name = "${resource_name}"
    cfn_type = ${cfn_type}
    deployment_mode = "${deployment_mode}"

    # Introspection metadata
    list_operation = ${list_operation}
    describe_operation = ${describe_operation}
    id_fields = ${id_params}
    summary_list_path = ${summary_list_path}
    summary_arn_field = ${arn_field}

    # ------------------------------------------------------------------
    # fetch_resource
    # ------------------------------------------------------------------
    def fetch_resource(self, arn: ARN) -> Mapping[str, Any]:
        """
        Call Describe*/Get* using IDs resolved from the ARN.

        ID Resolution Rules:
          1) id_fields ending in "Id"     → hierarchy match (e.g. InstanceId)
          2) id_fields ending in "Arn"    → full ARN
          3) id_fields ending in "Name"   → ARN.resource_id
          4) fallback: map last N ARN parts → id_fields

        For synthetic resources that don't have a native ARN, the ARN passed
        in is typically an "anchor" (e.g., the parent instance ARN).
        """
        if not self.describe_operation:
            raise RuntimeError(f"No describe_operation for {self.resource_name}")

        parts = arn.resource_parts
        values: dict[str, str] = {}
        hierarchy = dict(arn.resource_hierarchy())

        for key in self.id_fields:
            kl = key.lower()

            # InstanceId → instance
            if kl.endswith("id"):
                base = kl[:-2]
                if base in hierarchy:
                    values[key] = hierarchy[base]
                    continue

            # ResourceArn → full ARN
            if kl.endswith("arn"):
                values[key] = arn.raw
                continue

            # FunctionName / TableName → resource_id
            if kl.endswith("name") and arn.resource_id:
                values[key] = arn.resource_id
                continue

        # Fallback: map last N ARN parts to remaining id_fields
        if self.id_fields and len(values) < len(self.id_fields):
            needed = len(self.id_fields) - len(values)
            if len(parts) >= needed:
                for key, val in zip(
                    [k for k in self.id_fields if k not in values],
                    parts[-needed:]
                ):
                    values.setdefault(key, val)

        log.debug(
            "Calling %s.%s for %s with params %s",
            self.service,
            self.describe_operation,
            arn,
            values,
        )

        client = self.client_for(arn)
        fn = getattr(client, self.describe_operation)
        return fn(**values)

    # ------------------------------------------------------------------
    # to_node
    # ------------------------------------------------------------------
    def to_node(self, arn: ARN, raw: Mapping[str, Any]) -> ResourceNode:
        """
        Convert the raw Describe*/Get* output into a ResourceNode.
        This is uniform across all generated resolvers.
        """

        # unwrap: {"ResourceName": {...}} → {...}
        inner = raw.get(self.resource_name) if isinstance(raw, Mapping) else None
        props = inner if isinstance(inner, Mapping) else raw

        rid = arn.resource_id or "Root"
        logical_id = f"{self.resource_name}_{rid}"
        referenced = extract_dependencies(props)

        return ResourceNode(
            logical_id=logical_id,
            service=self.service,
            cfn_type=self.cfn_type,
            properties=dict(props),
            referenced_arns=referenced,
            classification=NodeClassification.RESOURCE,
            arns={"Primary": arn},  # backward compatible
        )
''')


# =====================================================================
# Utility
# =====================================================================
def _guess_stub_client_name(service: str) -> str:
    """
    Heuristic for choosing the correct mypy-boto3 client class.
    Works for most core services; manual fix for unusual ones.
    """
    parts = [p for p in service.replace("-", "_").split("_") if p]
    camel = "".join(p.capitalize() for p in parts)
    return f"{camel}Client"


def _arn_resource_key(resource_name: str) -> str:
    """
    Convert a CamelCase resource name into the ARN resource_type form
    (lowercase, hyphen-separated).
    Example: ContactFlow -> contact-flow
    """
    # Normalize separators first
    slug = resource_name.replace("_", "-").replace(" ", "-")
    # Insert hyphens before capitals preceded by lowercase/digits
    slug = re.sub(r"([a-z0-9])([A-Z])", r"\1-\2", slug)
    # Split acronym + word boundaries (e.g., IAMRole -> IAM-Role)
    slug = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1-\2", slug)
    slug = slug.lower()
    slug = re.sub(r"-{2,}", "-", slug).strip("-")
    return slug


# =====================================================================
# Main generation function
# =====================================================================
def generate_resolvers(schema_path: str, output_dir: str) -> None:
    data = json.loads(Path(schema_path).read_text(encoding="utf-8"))

    service: str = data["service"]
    resources: Dict[str, Dict[str, Any]] = data["resources"]

    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    stub_client = _guess_stub_client_name(service)

    for resource_name, r in resources.items():
        operations = r.get("operations") or {}
        describe_op = operations.get("describe")

        # Must have a describe/get op; list-only resources are ignored.
        if not describe_op:
            continue

        # Output file + class name
        resource_key = _arn_resource_key(resource_name)
        class_name = f"{service.capitalize()}{resource_name}Resolver"
        filename_key = resource_key.replace("-", "_")
        filename = f"{service}_{filename_key}_resolver.py"

        # Deployment mode priority: L2 > CFN > boto3
        if r.get("deployable_via_l2"):
            deployment_mode = "l2"
        elif r.get("deployable_via_cfn"):
            deployment_mode = "cfn"
        else:
            deployment_mode = "boto3"

        list_ops = operations.get("list") or []
        list_op = list_ops[0] if list_ops else None

        code = TEMPLATE.substitute(
            service=service,
            resource_key=resource_key,
            resource_name=resource_name,
            class_name=class_name,
            cfn_type=repr(r.get("cfn_type")),
            deployment_mode=deployment_mode,
            list_operation=repr(list_op),
            describe_operation=repr(describe_op),
            id_params=repr(r.get("id_params") or []),
            summary_list_path=repr(r.get("list_result_path")),
            arn_field=repr(r.get("arn_field")),
            stub_client=stub_client,
        )

        (out / filename).write_text(code, encoding="utf-8")
        print(f"Generated resolver: {filename}")

    print("Done.")


# =====================================================================
# CLI
# =====================================================================
if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate resolver classes from a service schema JSON.",
    )
    parser.add_argument("--schema", required=True, help="Path to schema JSON from service_introspector")
    parser.add_argument("--out", required=True, help="Output directory for generated resolvers")
    args = parser.parse_args()

    generate_resolvers(args.schema, args.out)
