from __future__ import annotations

from poc.resolvers.base_resolver import BaseResolver
from poc.resolvers.registry import register_resolver

# Optional: enable service-specific mypy-boto3 stubs.
# Uncomment if you have the correct stub package:
# from mypy_boto3_apigateway import ApigatewayClient as Boto3Client  # type: ignore[import]
# Otherwise fallback:
# from botocore.client import BaseClient as Boto3Client

@register_resolver("apigateway:domain-name")
class ApigatewayDomainNameResolver(BaseResolver):
    """
    Auto-generated resolver for apigateway:DomainName.
    Generated by tools/service_introspector.py.
    """

    service = "apigateway"
    resource_type = "domain-name"
    resource_name = "DomainName"
    cfn_type = "AWS::ApiGateway::DomainName"
    deployment_mode = "cfn"

    # Introspection metadata
    list_operation = 'get_domain_names'
    describe_operation = 'get_domain_name'
    id_fields = ['domainName', 'domainNameId']
    summary_list_path = 'items'
    summary_arn_field = 'domainNameArn'



@register_resolver("apigateway:domain-name-access-association")
class ApigatewayDomainNameAccessAssociationResolver(BaseResolver):
    """
    Auto-generated resolver for apigateway:DomainNameAccessAssociation.
    Generated by tools/service_introspector.py.
    """

    service = "apigateway"
    resource_type = "domain-name-access-association"
    resource_name = "DomainNameAccessAssociation"
    cfn_type = None
    deployment_mode = "boto3"

    # Introspection metadata
    list_operation = 'get_domain_name_access_associations'
    describe_operation = 'get_domain_name_access_associations'
    id_fields = []
    summary_list_path = 'items'
    summary_arn_field = 'domainNameAccessAssociationArn'

