from __future__ import annotations

from poc.resolvers.base_resolver import BaseResolver
from poc.resolvers.registry import register_resolver

# Optional: enable service-specific mypy-boto3 stubs.
# Uncomment if you have the correct stub package:
# from mypy_boto3_cloudformation import CloudformationClient as Boto3Client  # type: ignore[import]
# Otherwise fallback:
# from botocore.client import BaseClient as Boto3Client

@register_resolver("cloudformation:type")
class CloudformationTypeResolver(BaseResolver):
    """
    Auto-generated resolver for cloudformation:Type.
    Generated by tools/service_introspector.py.
    """

    service = "cloudformation"
    resource_type = "type"
    resource_name = "Type"
    cfn_type = None
    deployment_mode = "boto3"

    # Introspection metadata
    list_operation = 'list_types'
    describe_operation = 'describe_type'
    id_fields = ['TypeName', 'Arn', 'VersionId', 'PublisherId']
    summary_list_path = 'TypeSummaries'
    summary_arn_field = 'TypeArn'


