from __future__ import annotations

from poc.resolvers.base_resolver import BaseResolver
from poc.resolvers.registry import register_resolver

# Optional: enable service-specific mypy-boto3 stubs.
# Uncomment if you have the correct stub package:
# from mypy_boto3_events import EventsClient as Boto3Client  # type: ignore[import]
# Otherwise fallback:
# from botocore.client import BaseClient as Boto3Client

@register_resolver("events:api-destination")
class EventsApiDestinationResolver(BaseResolver):
    """
    Auto-generated resolver for events:ApiDestination.
    Generated by tools/service_introspector.py.
    """

    service = "events"
    resource_type = "api-destination"
    resource_name = "ApiDestination"
    cfn_type = "AWS::Events::ApiDestination"
    deployment_mode = "cfn"

    # Introspection metadata
    list_operation = 'list_api_destinations'
    describe_operation = 'describe_api_destination'
    id_fields = ['Name']
    summary_list_path = 'ApiDestinations'
    summary_arn_field = 'ApiDestinationArn'



@register_resolver("events:connection")
class EventsConnectionResolver(BaseResolver):
    """
    Auto-generated resolver for events:Connection.
    Generated by tools/service_introspector.py.
    """

    service = "events"
    resource_type = "connection"
    resource_name = "Connection"
    cfn_type = "AWS::Events::Connection"
    deployment_mode = "cfn"

    # Introspection metadata
    list_operation = 'list_connections'
    describe_operation = 'describe_connection'
    id_fields = ['Name']
    summary_list_path = 'Connections'
    summary_arn_field = 'ConnectionArn'



@register_resolver("events:endpoint")
class EventsEndpointResolver(BaseResolver):
    """
    Auto-generated resolver for events:Endpoint.
    Generated by tools/service_introspector.py.
    """

    service = "events"
    resource_type = "endpoint"
    resource_name = "Endpoint"
    cfn_type = "AWS::Events::Endpoint"
    deployment_mode = "cfn"

    # Introspection metadata
    list_operation = 'list_endpoints'
    describe_operation = 'describe_endpoint'
    id_fields = ['Name']
    summary_list_path = 'Endpoints'
    summary_arn_field = 'Arn'



@register_resolver("events:event-source")
class EventsEventSourceResolver(BaseResolver):
    """
    Auto-generated resolver for events:EventSource.
    Generated by tools/service_introspector.py.
    """

    service = "events"
    resource_type = "event-source"
    resource_name = "EventSource"
    cfn_type = None
    deployment_mode = "boto3"

    # Introspection metadata
    list_operation = 'list_event_sources'
    describe_operation = 'describe_event_source'
    id_fields = ['Name']
    summary_list_path = 'EventSources'
    summary_arn_field = 'Arn'



@register_resolver("events:partner-event-source")
class EventsPartnerEventSourceResolver(BaseResolver):
    """
    Auto-generated resolver for events:PartnerEventSource.
    Generated by tools/service_introspector.py.
    """

    service = "events"
    resource_type = "partner-event-source"
    resource_name = "PartnerEventSource"
    cfn_type = None
    deployment_mode = "boto3"

    # Introspection metadata
    list_operation = 'list_partner_event_sources'
    describe_operation = 'describe_partner_event_source'
    id_fields = ['Name']
    summary_list_path = 'PartnerEventSources'
    summary_arn_field = 'Arn'



@register_resolver("events:rule")
class EventsRuleResolver(BaseResolver):
    """
    Auto-generated resolver for events:Rule.
    Generated by tools/service_introspector.py.
    """

    service = "events"
    resource_type = "rule"
    resource_name = "Rule"
    cfn_type = "AWS::Events::Rule"
    deployment_mode = "cfn"

    # Introspection metadata
    list_operation = 'list_rules'
    describe_operation = 'describe_rule'
    id_fields = ['Name', 'EventBusName']
    summary_list_path = 'Rules'
    summary_arn_field = 'Arn'

