from __future__ import annotations

from poc.resolvers.base_resolver import BaseResolver
from poc.resolvers.registry import register_resolver

# Optional: enable service-specific mypy-boto3 stubs.
# Uncomment if you have the correct stub package:
# from mypy_boto3_kms import KmsClient as Boto3Client  # type: ignore[import]
# Otherwise fallback:
# from botocore.client import BaseClient as Boto3Client

@register_resolver("kms:key")
class KmsKeyResolver(BaseResolver):
    """
    Auto-generated resolver for kms:Key.
    Generated by tools/service_introspector.py.
    """

    service = "kms"
    resource_type = "key"
    resource_name = "Key"
    cfn_type = "AWS::KMS::Key"
    deployment_mode = "cfn"

    # Introspection metadata
    list_operation = 'list_keys'
    describe_operation = 'describe_key'
    id_fields = ['KeyId']
    summary_list_path = 'Keys'
    summary_arn_field = 'KeyArn'

