from __future__ import annotations

from poc.resolvers.base_resolver import BaseResolver
from poc.resolvers.registry import register_resolver

# Optional: enable service-specific mypy-boto3 stubs.
# Uncomment if you have the correct stub package:
# from mypy_boto3_lambda import LambdaClient as Boto3Client  # type: ignore[import]
# Otherwise fallback:
# from botocore.client import BaseClient as Boto3Client

@register_resolver("lambda:code-signing-config")
class LambdaCodeSigningConfigResolver(BaseResolver):
    """
    Auto-generated resolver for lambda:CodeSigningConfig.
    Generated by tools/service_introspector.py.
    """

    service = "lambda"
    resource_type = "code-signing-config"
    resource_name = "CodeSigningConfig"
    cfn_type = None
    deployment_mode = "boto3"

    # Introspection metadata
    list_operation = 'list_code_signing_configs'
    describe_operation = 'get_code_signing_config'
    id_fields = ['CodeSigningConfigArn']
    summary_list_path = 'CodeSigningConfigs'
    summary_arn_field = 'CodeSigningConfigArn'



@register_resolver("lambda:event-source-mapping")
class LambdaEventSourceMappingResolver(BaseResolver):
    """
    Auto-generated resolver for lambda:EventSourceMapping.
    Generated by tools/service_introspector.py.
    """

    service = "lambda"
    resource_type = "event-source-mapping"
    resource_name = "EventSourceMapping"
    cfn_type = None
    deployment_mode = "boto3"

    # Introspection metadata
    list_operation = 'list_event_source_mappings'
    describe_operation = 'get_event_source_mapping'
    id_fields = ['UUID']
    summary_list_path = 'EventSourceMappings'
    summary_arn_field = 'EventSourceArn'



@register_resolver("lambda:function")
class LambdaFunctionResolver(BaseResolver):
    """
    Auto-generated resolver for lambda:Function.
    Generated by tools/service_introspector.py.
    """

    service = "lambda"
    resource_type = "function"
    resource_name = "Function"
    cfn_type = None
    deployment_mode = "boto3"

    # Introspection metadata
    list_operation = 'list_functions'
    describe_operation = 'get_function'
    id_fields = ['FunctionName']
    summary_list_path = 'Functions'
    summary_arn_field = 'FunctionArn'



@register_resolver("lambda:function-configuration")
class LambdaFunctionConfigurationResolver(BaseResolver):
    """
    Auto-generated resolver for lambda:FunctionConfiguration.
    Generated by tools/service_introspector.py.
    """

    service = "lambda"
    resource_type = "function-configuration"
    resource_name = "FunctionConfiguration"
    cfn_type = None
    deployment_mode = "boto3"

    # Introspection metadata
    list_operation = 'get_function_configuration'
    describe_operation = 'get_function_configuration'
    id_fields = ['FunctionName']
    summary_list_path = 'Layers'
    summary_arn_field = 'Arn'



@register_resolver("lambda:function-event-invoke-config")
class LambdaFunctionEventInvokeConfigResolver(BaseResolver):
    """
    Auto-generated resolver for lambda:FunctionEventInvokeConfig.
    Generated by tools/service_introspector.py.
    """

    service = "lambda"
    resource_type = "function-event-invoke-config"
    resource_name = "FunctionEventInvokeConfig"
    cfn_type = "AWS::Lambda::EventInvokeConfig"
    deployment_mode = "cfn"

    # Introspection metadata
    list_operation = 'list_function_event_invoke_configs'
    describe_operation = 'get_function_event_invoke_config'
    id_fields = ['FunctionName']
    summary_list_path = 'FunctionEventInvokeConfigs'
    summary_arn_field = 'FunctionArn'



@register_resolver("lambda:function-url-config")
class LambdaFunctionUrlConfigResolver(BaseResolver):
    """
    Auto-generated resolver for lambda:FunctionUrlConfig.
    Generated by tools/service_introspector.py.
    """

    service = "lambda"
    resource_type = "function-url-config"
    resource_name = "FunctionUrlConfig"
    cfn_type = "AWS::Lambda::Url"
    deployment_mode = "cfn"

    # Introspection metadata
    list_operation = 'list_function_url_configs'
    describe_operation = 'get_function_url_config'
    id_fields = ['FunctionName']
    summary_list_path = 'FunctionUrlConfigs'
    summary_arn_field = 'FunctionArn'



@register_resolver("lambda:layer")
class LambdaLayerResolver(BaseResolver):
    """
    Auto-generated resolver for lambda:Layer.
    Generated by tools/service_introspector.py.
    """

    service = "lambda"
    resource_type = "layer"
    resource_name = "Layer"
    cfn_type = "AWS::Lambda::LayerVersion"
    deployment_mode = "cfn"

    # Introspection metadata
    list_operation = 'list_layers'
    describe_operation = 'get_layer_version'
    id_fields = ['LayerName']
    summary_list_path = 'Layers'
    summary_arn_field = 'LayerArn'



@register_resolver("lambda:layer-version")
class LambdaLayerVersionResolver(BaseResolver):
    """
    Auto-generated resolver for lambda:LayerVersion.
    Generated by tools/service_introspector.py.
    """

    service = "lambda"
    resource_type = "layer-version"
    resource_name = "LayerVersion"
    cfn_type = "AWS::Lambda::LayerVersion"
    deployment_mode = "cfn"

    # Introspection metadata
    list_operation = 'list_layer_versions'
    describe_operation = 'get_layer_version'
    id_fields = ['LayerName']
    summary_list_path = 'LayerVersions'
    summary_arn_field = 'LayerVersionArn'

