from __future__ import annotations

from poc.resolvers.base_resolver import BaseResolver
from poc.resolvers.registry import register_resolver

# Optional: enable service-specific mypy-boto3 stubs.
# Uncomment if you have the correct stub package:
# from mypy_boto3_s3 import S3Client as Boto3Client  # type: ignore[import]
# Otherwise fallback:
# from botocore.client import BaseClient as Boto3Client

@register_resolver("s3:bucket")
class S3BucketResolver(BaseResolver):
    """
    Auto-generated resolver for s3:Bucket.
    Generated by tools/service_introspector.py.
    """

    service = "s3"
    resource_type = "bucket"
    resource_name = "Bucket"
    cfn_type = "AWS::S3::Bucket"
    deployment_mode = "cfn"

    # Introspection metadata
    list_operation = 'list_buckets'
    describe_operation = 'get_bucket_abac'
    id_fields = []
    summary_list_path = 'Buckets'
    summary_arn_field = 'BucketArn'

